### ISSUE TITLE
persistent-collections

### ISSUE THREAD

**Issue by Xenoage** [marian-margeta/GraphQLTest#1]
Hi!

I'm very sorry for abusing this issue functionality to get in contact with you. You may delete this entry of course.
Are you the author of the persistent-collections library?

I'm very interested to reactivate and improve this project.
Persistent data structures will be getting increasing attention, now that C# 9 provides records.
Is there any material I can build upon, except the archived material from https://archive.codeplex.com/?p=persistent ?
Or do you have any plans for yourself to work further on it?

Thank you very much!
If you want to reply, you can also send me an e-mail to andi@xenoage.com 

Andi

**Comment by marian-margeta** [comment]
Hi @Xenoage,

well, this project is really old and it has not been maintained since 2015. It is easy to port those collections to net5.0 and when I compared them with `System.Collections.Immutable` 5.0.0, the difference in performance was not as significant as 5 years ago. I mean they are still much better in mem and slightly better in cpu consumption but I am not sure if it is worth it. So I would recommend you to use standard `System.Collections.Immutable` in most cases. It is a part of a framework `Microsoft.NETCore.App` which is normally included in runtime.  

However, it might make sense to use them in performance critical solutions. `persistent-collections` are slightly modified implementation of Rich Hickey's Persistent Vectors and maps in Clojure lang. I think his concept is one of the best. The original code in java can be found in clojure repo:
https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/PersistentVector.java
On the other hand, `System.Collections.Immutable` are based on more conservative binary tree solution
https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.Node.cs

Now I don't have any plans to work further on it. Microsoft's implementation of immutable collection 5+ years ago was really poor so I just wanted to offer a better solution. It seems that since then they made a step forward. But of course you can revive and improve the project if you want :)

**Comment by Xenoage** [comment]
Thank you very much for your detailed response. It's very useful for me to know that your tests showed that .NET 5.0 System.Collections.Immutable are good enough. In this case, I think we will use this standard solution and not reactivate the persistent-collections project. Again, thanks!
